home:
    path: /
    defaults: { _controller: AppBundle:Default:home }


pain:
    path: /pain
    defaults: { _controller: AppBundle:Default:pain }


more_info:
    path: /more_info
    defaults: { _controller: AppBundle:Default:more_info }

results:
    path: /results
    defaults: { _controller: AppBundle:Default:results }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
